volumes:
  data_privatebin:
    external: false

services:
  traefik:
    image: traefik:v3
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    labels:
      - traefik.enable=false

  privatebin:
    image: privatebin/nginx-fpm-alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.privatebin.entrypoints=web
      - traefik.http.routers.privatebin.rule=Host(`privatebin.dev.local`)
      - traefik.http.routers.privatebin-tls.tls=true
      - traefik.http.routers.privatebin-tls.entrypoints=websecure
      - traefik.http.routers.privatebin-tls.rule=Host(`privatebin.dev.local`)
      - traefik.http.services.privatebin.loadbalancer.server.port=8080
